name: WIS25
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - blinker==1.9.0
      - click==8.1.8
      - dnspython==2.7.0
      - dotenv==0.9.9
      - flask==3.1.0
      - flask-cors==5.0.1
      - flask-pymongo==3.0.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - numpy==2.2.4
      - pymongo==4.12.0
      - python-dotenv==1.1.0
      - werkzeug==3.1.3
